version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest-api
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-container
    ports:
      - "3001:3001"
    depends_on:
      - mysql



#version: "3.8"
#services:
#  database:
#    container_name: db
#    image: postgres:14.2
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_HOST_AUTH_METHOD
#  backend:
#    container_name: api
#    build:
#      dockerfile: Dockerfile
#      context: .
#    restart: on-failure
#    depends_on:
#      - database
#    ports:
#      - "3000:3000"
#    environment:
#      - DATABASE_HOST=database
#      - DATABASE_PORT=5432
#      - DATABASE_USER=postgres
#      - DATABASE_PASSWORD
#      - DATABASE_NAME
#      - DATABASE_SYNCHRONIZE
#      - NODE_ENV