version: '3'

services:
  #  api:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    ports:
  #      - '3001:3001'
  #    container_name: api
  #    restart: always
  #    volumes:
  #      - api-logs:/usr/src/node-api/logs:rw
  #    environment:
  #      - NODE_ENV=development
  #    depends_on:
  #      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest-api
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./dados_mysql:/var/lib/mysql
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  api-logs:
  pg-data: